# Generated by Django 3.2.16 on 2022-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('header_menu', 'Верхнее меню')], default='', max_length=100, verbose_name='Тип меню'),
        ),
    ]
