# Generated by Django 3.2.16 on 2022-11-06 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('min_price', models.CharField(max_length=50)),
                ('hotel_type', models.CharField(choices=[('hotel', 'Гостиница'), ('motel', 'Мотель'), ('apartment', 'Апартаменты')], max_length=100)),
                ('stars', models.IntegerField()),
                ('rating', models.FloatField()),
                ('swimming_pool', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('wi_fi', models.BooleanField()),
                ('slug', models.SlugField()),
                ('hotel_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_items', to='hotels.hotellistpage', verbose_name='Страница (привязка)')),
            ],
        ),
    ]
