# Generated by Django 3.2.16 on 2022-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='hotel_type',
            field=models.CharField(choices=[('hotel', 'Гостиница'), ('motel', 'Мотель'), ('apartment', 'Апартаменты')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='min_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='parking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='swimming_pool',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='hotelpage',
            name='wi_fi',
            field=models.BooleanField(null=True),
        ),
    ]
