# Generated by Django 3.2.16 on 2022-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20221106_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelpage',
            name='max_price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotelpage',
            name='hotel_type',
            field=models.CharField(choices=[('Гостиница', 'Гостиница'), ('Мотель', 'Мотель'), ('Апартаменты', 'Апартаменты')], max_length=100, null=True),
        ),
    ]
