# Generated by Django 3.2.16 on 2022-11-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221105_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='home_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasons_items', to='home.homepage', verbose_name='Страница (привязка)'),
        ),
    ]
