# Generated by Django 3.2.16 on 2022-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_reasons_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='recommendations',
            field=models.JSONField(null=True),
        ),
    ]
