# Generated by Django 3.2.16 on 2022-11-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20221105_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='recommendation_description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='recommendation_description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='recommendation_description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='recommendation_title_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='recommendation_title_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='recommendation_title_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
