# Generated by Django 3.2.16 on 2022-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20221105_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(verbose_name='Дата заезда')),
                ('output_date', models.DateField(verbose_name='Дата выезда')),
                ('parents', models.PositiveSmallIntegerField(verbose_name='Взрослые')),
                ('childrens', models.PositiveSmallIntegerField(verbose_name='Дети')),
            ],
        ),
    ]
