# Generated by Django 3.2.16 on 2022-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221107_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='date_in',
            field=models.DateField(blank=True, verbose_name='Дата заезда'),
        ),
    ]
