# Generated by Django 3.2.16 on 2022-11-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_bron_date_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='date_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='date_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
    ]
